### ISSUE TITLE
Example notebook

### ISSUE THREAD

**Issue by abitrolly** [innovationOUtside/ipython_magic_sqlalchemy_schemadisplay#2]
@psychemedia can you commit example notebook to see how GitHub renders it?

**Comment by psychemedia** [comment]
@abitrolly 
Thanks for the prompt - I've been meaning to document this for ages... Will try to press on with it over next few days. For now, there is a quick demo notebook in `notebooks` folder and the repo is Binderised, so you should be able to run it on MyBinder.

**Comment by abitrolly** [comment]
https://github.com/innovationOUtside/ipython_magic_sqlalchemy_schemadisplay/blob/master/notebooks/SchemaDemo.ipynb is enough, thanks.

https://mybinder.org/v2/gh/innovationOUtside/ipython_magic_sqlalchemy_schemadisplay/master?filepath=notebooks%2FSchemaDemo.ipynb is also available.
